// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrhl8GMScMuTcRVWQHtBvBCMogaDcu7gw',
    appId: '1:45346470757:web:dbf24e2fc07e2773687f8c',
    messagingSenderId: '45346470757',
    projectId: 'neighborhood-safety-network',
    authDomain: 'neighborhood-safety-network.firebaseapp.com',
    storageBucket: 'neighborhood-safety-network.firebasestorage.app',
    measurementId: 'G-ZQ9RXMK33L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd2d5v8CJM2neKkjfKOighuPRHtPtYmPM',
    appId: '1:45346470757:android:207b53ca57834439687f8c',
    messagingSenderId: '45346470757',
    projectId: 'neighborhood-safety-network',
    storageBucket: 'neighborhood-safety-network.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM_KCkIiDkw2f34tUxkbTPT0PyX6T3tR8',
    appId: '1:45346470757:ios:c001ac8146373e44687f8c',
    messagingSenderId: '45346470757',
    projectId: 'neighborhood-safety-network',
    storageBucket: 'neighborhood-safety-network.firebasestorage.app',
    iosBundleId: 'com.example.neighborhoodSafetyNetwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM_KCkIiDkw2f34tUxkbTPT0PyX6T3tR8',
    appId: '1:45346470757:ios:c001ac8146373e44687f8c',
    messagingSenderId: '45346470757',
    projectId: 'neighborhood-safety-network',
    storageBucket: 'neighborhood-safety-network.firebasestorage.app',
    iosBundleId: 'com.example.neighborhoodSafetyNetwork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrhl8GMScMuTcRVWQHtBvBCMogaDcu7gw',
    appId: '1:45346470757:web:c0596ae0fa14bba3687f8c',
    messagingSenderId: '45346470757',
    projectId: 'neighborhood-safety-network',
    authDomain: 'neighborhood-safety-network.firebaseapp.com',
    storageBucket: 'neighborhood-safety-network.firebasestorage.app',
    measurementId: 'G-2891LFGRG1',
  );
}